# Advanced Logging Example Configuration

# HTTP Client configuration with verbose logging enabled
httpclient:
  # Connection pooling settings
  max_idle_conns: 50
  max_idle_conns_per_host: 5
  idle_conn_timeout: "60s"
  
  # Timeout settings
  request_timeout: "15s"
  tls_timeout: "5s"
  
  # Other settings
  disable_compression: false
  disable_keep_alives: false
  
  # Enable detailed verbose logging
  verbose: true
  
  # Advanced verbose logging options
  verbose_options:
    log_headers: true           # Log request and response headers
    log_body: true             # Log request and response bodies
    max_body_log_size: 5120    # Maximum size of logged bodies (5KB)
    log_to_file: true          # Log to files instead of just application logger
    log_file_path: "./logs"    # Directory for log files

# HTTP Server configuration  
httpserver:
  host: "localhost"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

# ChiMux configuration
chimux:
  allowed_origins: ["*"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["*"]
  allow_credentials: true
  max_age: 86400

# Reverse Proxy configuration
reverseproxy:
  backend_services:
    httpbin: "https://httpbin.org"
  routes:
    "/proxy/httpbin": "httpbin"
    "/proxy/httpbin/*": "httpbin"
  default_backend: "httpbin"
