# Multi-Engine EventBus Example Configuration
# This configuration demonstrates multi-engine EventBus setup with intelligent routing

# Application configuration
name: "Multi-Engine EventBus Demo"
environment: "development"

# EventBus configuration with multiple engines and routing
eventbus:
  engines:
    # Memory engine optimized for fast processing (user/auth events)
    - name: "memory-fast"
      type: "memory"
      config:
        maxEventQueueSize: 500
        defaultEventBufferSize: 10
        workerCount: 3
        retentionDays: 1
    
    # Redis engine for durable messaging (system/health events)  
    - name: "redis-durable"
      type: "redis"
      config:
        url: "redis://localhost:6379"
        db: 0
        poolSize: 10
    
    # Kafka engine for analytics/metrics (distributed processing)
    - name: "kafka-analytics" 
      type: "kafka"
      config:
        brokers:
          - "localhost:9092"
        groupId: "multi-engine-demo"
    
    # Custom memory engine with metrics (fallback for all other topics)
    - name: "memory-reliable"
      type: "custom"
      config:
        enableMetrics: true
        maxEventQueueSize: 2000
        defaultEventBufferSize: 50
        metricsInterval: "30s"
  
  # Topic-based routing rules (processed in order)
  routing:
    # User and authentication events → fast memory engine
    - topics: ["user.*", "auth.*"]
      engine: "memory-fast"
    
    # Analytics and metrics events → Kafka engine  
    - topics: ["analytics.*", "metrics.*"]
      engine: "kafka-analytics"
    
    # System and health events → Redis engine
    - topics: ["system.*", "health.*"] 
      engine: "redis-durable"
    
    # All other topics → reliable memory engine with metrics
    - topics: ["*"]
      engine: "memory-reliable"