# Instance-Aware Database Configuration Example
# This example demonstrates instance-aware environment variable configuration
# The YAML values below are overridden by DB_*_* environment variables set in main.go

# Basic application settings
app:
  name: "Instance-Aware Database Example"
  environment: "development"

database:
  default: "primary"
  connections:
    primary:
      driver: "sqlite3"  # Will be overridden by DB_PRIMARY_DRIVER env var 
      dsn: "./default_primary.db"     # Will be overridden by DB_PRIMARY_DSN env var
    secondary:
      driver: "sqlite3"  # Will be overridden by DB_SECONDARY_DRIVER env var
      dsn: "./default_secondary.db"     # Will be overridden by DB_SECONDARY_DSN env var
    cache:
      driver: "sqlite3"  # Will be overridden by DB_CACHE_DRIVER env var
      dsn: ":memory:"     # Will be overridden by DB_CACHE_DSN env var