# Base configuration shared across all environments
app_name: "Base Config Example"
environment: "base"

# Database configuration
database:
  host: "localhost"
  port: 5432
  name: "base_app_db"
  username: "app_user"
  password: "base_password"

# Feature flags
features:
  logging: true
  metrics: false
  caching: true
  debug: true

# Server configuration  
server:
  host: "localhost"
  port: 8080
  timeout: 30
  max_connections: 100

# External services
external_services:
  redis:
    enabled: false
    host: "localhost"
    port: 6379
  
  rabbitmq:
    enabled: false
    host: "localhost" 
    port: 5672