reverseproxy:
  backend_services:
    backend1: "http://backend1.example.com"
    backend2: "http://backend2.example.com"
  default_backend: "backend1"
  feature_flag_service_url: "http://featureflags.example.com"
  # Example composite routes configuration
  composite_routes:
    "/api/composite/data":
      pattern: "/api/composite/data"
      backends:
        - "backend1"
        - "backend2"
      strategy: "merge"
