name: Race Detector

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  race-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          check-latest: true

      - name: Cache Go build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Make race script executable
        run: chmod +x scripts/test_race.sh

      - name: Run race tests
        env:
          GORACE: halt_on_error=1
          CGO_ENABLED: 0
        run: ./scripts/test_race.sh

      - name: Build examples (smoke)
        run: |
          set -euo pipefail
          for ex in examples/*/; do
            if [ -f "$ex/go.mod" ]; then
              echo "Building $ex";
              (cd "$ex" && go build ./...);
            fi
          done
